spring.application.name=japi

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

server.port=8080
server.servlet.session.timeout=30m
server.error.whitelabel.enabled=false
server.error.include-exception=true
server.error.include-stacktrace=always


# TODO: 서버 환경설정으로 변경 및 git 로그에 기록 남았으므로 비밀번호도 변경
#spring.datasource.url="jdbc:log4jdbc:mariadb://121.129.195.32:33064/japi?characterEncoding=UTF-8&allowMultiQueries=true"
#spring.datasource.username="japi"
#spring.datasource.password="zkzkdh99"
#spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# TODO: 여기 왜 경고 뜨는지 확인
jwt.secret=${JWT_SECRET_KEY:default-dev-secret}
jwt.expiration=${JWT_EXPIRATION:86400000}


logging.level.root=info
logging.level.org.springframework.jdbc=trace