spring.application.name=japi

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

server.port=8080
server.servlet.session.timeout=30m
server.error.whitelabel.enabled=false
server.error.include-exception=true
server.error.include-stacktrace=always

spring.config.activate.on-profile="LOCAL"
spring.datasource.url="jdbc:log4jdbc:mariadb://121.129.195.32:33064/japi?characterEncoding=UTF-8&allowMultiQueries=true"
spring.datasource.username="japi"
spring.datasource.password="zkzkdh99"
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

logging.level.root=info
logging.level.org.springframework.jdbc=trace